In [2]:
import torch
import numpy as np

In [14]:
x = torch.tensor([[0.0, 0.0, 0.0]], requires_grad=True)
p = torch.tensor([
    [1.0, 2.0],
    [3.0, 4.0],
    [5.0, 6.0]
])
y = x.mm(p)
print(y)
z = torch.exp(y)
g = z.sum()

tensor([[0., 0.]], grad_fn=<MmBackward>)


In [7]:
g.backward()

In [8]:
x.grad

tensor([[ 3.,  7., 11.]])

In [41]:
x = torch.tensor([[0.3, 1.0, 0.0]], requires_grad=True)
p = torch.tensor([
    [1.0, 2.0],
    [3.0, 4.0],
    [5.0, 6.0]
])
y = x.mm(p) ** 2
print(y)
z = torch.exp(y)
g = z.sum()

tensor([[10.8900, 21.1600]], grad_fn=<PowBackward0>)


In [42]:
y.backward(torch.tensor([[1.0, 1.0]]))

In [43]:
x.grad

tensor([[25.0000, 56.6000, 88.2000]])

In [44]:
x

tensor([[0.3000, 1.0000, 0.0000]], requires_grad=True)

In [46]:
torch.tensor([1.0, 2.0]).sum().item()

3.0